spring.application.name=inventario_services
server.port=8081

# Base de datos
spring.profiles.active=local

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.error.include-message=always
server.error.include-binding-errors=always