spring.application.name=producto_services

##spring.datasource.url=jdbc:postgresql://localhost:5432/producto_db
spring.datasource.url=jdbc:postgresql://producto-db:5432/producto_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect